# -*- coding: utf-8 -*-
"""checkpoint_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ud2DqRcH7Fmr8ZqsCHRTbXiOVCtRTiOR
"""

import os
import torch

# --- CLASSE CHECKPOINT MANAGER AVANZATA ---
class CheckpointManager:
    def __init__(self, save_dir='checkpoints', model_name='best_facenet_hybrid.pth'):
        self.save_dir = save_dir
        self.file_path = os.path.join(save_dir, model_name)
        self.best_loss = float('inf')

        if not os.path.exists(self.save_dir):
            os.makedirs(self.save_dir)

    def save_checkpoint(self, model, optimizer, epoch, current_loss):
        """
        Salva un dizionario completo solo se la loss migliora.
        """
        if current_loss < self.best_loss:
            print(f"   >>> Record Loss! ({self.best_loss:.4f} -> {current_loss:.4f}). Salvataggio checkpoint completo...")
            self.best_loss = current_loss

            # Creiamo il dizionario con tutto ciò che serve per riprendere
            checkpoint = {
                'epoch': epoch + 1,             # Salviamo la prossima epoca da fare
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'best_loss': self.best_loss
            }
            torch.save(checkpoint, self.file_path)
        else:
            print(f"   >>> Nessun miglioramento (Best: {self.best_loss:.4f}).")

    def load_resume(self, model, optimizer):
        """
        Controlla se esiste un checkpoint, lo carica e restituisce l'epoca di partenza.
        """
        if os.path.isfile(self.file_path):
            print(f"--- Trovato checkpoint: {self.file_path} ---")
            
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            checkpoint = torch.load(self.file_path, map_location=device)

            # 1. Carica pesi modello
            model.load_state_dict(checkpoint['model_state_dict'])

            # 2. Carica stato ottimizzatore (momentum, learning rate interni, etc.)
            optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

            # 3. Recupera info training
            start_epoch = checkpoint['epoch']
            self.best_loss = checkpoint['best_loss']

            print(f"--- Riprendo dall'epoca {start_epoch} con Best Loss: {self.best_loss:.4f} ---")
            return start_epoch
        else:
            print("--- Nessun checkpoint trovato. Inizio training da zero. ---")
            return 0