# -*- coding: utf-8 -*-
"""trainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en5IsDrltHsKKqflIf0ntAs3YHbdKdXw
"""

import torch

class Trainer:
    def __init__(self,
                 model,
                 optimizer,
                 criterion,
                 checkpoint_manager,
                 device,
                 train_loader,
                 train_step_fn,
                 val_epoch_fn,
                 val_loader=None,
                 epochs=10,
                 scheduler=None):
        """
        Trainer generico per PyTorch.

        Args:
            model: Il modello PyTorch.
            optimizer: L'ottimizzatore.
            criterion: La funzione di loss (es. TripletMarginLoss, CrossEntropyLoss).
            checkpoint_manager: Gestore salvataggi (deve avere save_checkpoint e load_resume).
            device: 'cuda' o 'cpu'.
            train_loader (DataLoader): DataLoader per il training.
            val_loader (DataLoader, optional): DataLoader per la validazione.
            train_step_fn (callable, optional): Funzione che gestisce il singolo step di training.
                                                Firma: (model, batch, criterion, device) -> loss
            val_epoch_fn (callable, optional): Funzione che gestisce l'intera epoca di validazione.
                                               Firma: (model, val_loader, criterion, device) -> (avg_loss, accuracy/metrics)
            epochs (int): Numero di epoche da aggiungere.
        """
        self.model = model
        self.optimizer = optimizer
        self.criterion = criterion
        self.manager = checkpoint_manager
        self.device = device
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.epochs_to_add = epochs
        self.train_step_fn = train_step_fn
        self.val_epoch_fn = val_epoch_fn
        self.model.to(self.device)
        self.scheduler = scheduler
        print(f"--- Trainer Inizializzato su {self.device} ---")

    def fit(self):
        # Carica checkpoint (pesi e stato optimizer)
        start_epoch = self.manager.load_resume(self.model, self.optimizer)
        end_epoch = start_epoch + self.epochs_to_add

        print("-" * 60)
        print(f"Inizio Training Session: Epoca {start_epoch+1} -> {end_epoch}")
        print("-" * 60)

        for epoch in range(start_epoch, end_epoch):
            # --- TRAIN ---
            self.model.train()
            total_train_loss = 0.0

            for batch_idx, batch in enumerate(self.train_loader):
                self.optimizer.zero_grad()

                # Deleghiamo il calcolo della loss alla funzione esterna
                loss = self.train_step_fn(self.model, batch, self.criterion, self.device)

                loss.backward()
                self.optimizer.step()
                total_train_loss += loss.item()

            avg_train_loss = total_train_loss / len(self.train_loader)

            # --- VALIDATION ---
            avg_val_loss, val_metric = 0.0, 0.0
            if self.val_loader and self.val_epoch_fn:
                avg_val_loss, val_metric = self.val_epoch_fn(
                    self.model, self.val_loader, self.criterion, self.device
                )

            # --- LOGGING ---
            print(f"Epoch [{epoch+1}/{end_epoch}]")
            print(f"   Train Loss: {avg_train_loss:.4f}")
            if self.val_loader:
                # val_metric potrebbe essere accuracy, f1, etc.
                print(f"   Val Loss:   {avg_val_loss:.4f} | Val Metric: {val_metric:.4f}")

            # --- SAVE ---
            # Salviamo passando la val_loss per eventuale "best model" logic nel manager
            self.manager.save_checkpoint(self.model, self.optimizer, epoch, avg_val_loss)

            # --- SCHEDULER STEP ---
            # Se lo scheduler esiste, fallo avanzare.
            # Se è di tipo "ReduceLROnPlateau", ha bisogno della metrica (avg_val_loss)
            if self.scheduler:
                if isinstance(self.scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                    self.scheduler.step(avg_val_loss)  # Passagli la loss di validazione!
                else:
                    self.scheduler.step()
            print("-" * 60)

        print("Training completato.")